version: 2

sources:
  - name: public
    tables:
      - name: objective
      - name: survey
      - name: user_data

models:
  - name: quiz_rating
    description: "quiz rating model"
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: survey_state
        tests:
          - accepted_values:
              values: ['done', 'incomplete']
      - name: avg_rating
        tests:
          - not_null

exposures:
  - name: completed_quiz_metrics
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: "The number of completed quiz"
    
    depends_on:
      - ref('quiz_rating')
      - source('public', 'user_data')
      
    owner:
      name: Data Engineer
      email: dataengineer@majoo.id

metrics:
  - name: completed_quiz
    label: Completed Quiz
    model: ref('quiz_rating')
    description: "The number of completed quiz"

    type: count
    sql: user_id

    # timestamp: signup_date
    # time_grains: [day, week, month]

    # dimensions:
    #   - user
    
    filters:
      - field: survey_state
        operator: '='
        value: "'done'"

    meta: {team: Data Engineer}
